source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'pg', '~> 0.18.4'
gem 'kaminari', '~> 0.17.0'
git 'https://github.com/mollie/mollie-api-ruby.git', :tag => 'v2.2.1' do
  gem 'mollie-api-ruby'
end

# Authentication
gem 'devise', '~> 4.7'
# Multi tenancy
gem 'apartment', '~> 2.1'

# Storing settings
gem "rails-settings-cached"

gem 'sidekiq', '~> 4.1', '>= 4.1.2'
# Sidekiq monitoring
gem 'sinatra', require: false
gem 'slim'
# Transactional email provider
gem 'mailjet', '~> 1.5', '>= 1.5.4'
gem 'httparty', '~> 0.13.7' #needed for a workaround, see https://github.com/mailjet/mailjet-gem/issues/140
# Render HTML source (for a form example)
gem 'coderay', '~> 1.1', '>= 1.1.2'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  gem "capybara"                           # simulate UI interactions
  gem 'selenium-webdriver', '~> 3.8'
  gem "factory_bot_rails", "~> 4.0"        # creates database entries
  gem 'database_cleaner', '~> 1.6'         # truncates database in between tests
  gem 'rspec-rails', '~> 3.7'              # BDD
  gem 'guard-rspec', '~> 4.7'              # automated testing
  gem 'terminal-notifier-guard', '~> 1.7'  # osx notification
  gem 'webmock', '~> 3.1'                  # mock external http calls

  gem 'faker', '~> 1.8'                    # generate fake data
  gem 'ci_reporter_rspec', '~> 1.0'        # Jenkins reports
  gem 'rails-controller-testing', '~> 1.0'
end

group :test do
  gem 'rspec-sidekiq'                      # testing background jobs
  gem 'rspec_junit_formatter', '~> 0.2.3'  # creating junit test reports (for CI server)
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

#For handling currency and its formatting
gem 'money-rails', '~>1'
