version: '2'
services:

  app:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/lindy-admin:develop
    ports:
      - "3000"
    volumes:
      - ../rails-app:/rails-app

  web:
    build:
      context: ..
      dockerfile: deployment/nginx/Dockerfile.dev
    image: todorus/lindy-admin:nginx-dev
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app:app
