version: '2'
services:

  app:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/lindy-admin:develop
    ports:
      - 3000
    volumes:
      - ../rails-app:/rails-app
    depends_on:
      - storage
    links:
      - storage:storage
    stdin_open: true
    tty: true
    command: /bin/bash

  storage:
   image: postgres:9.6.3
   environment:
     - POSTGRES_USER=lindy
     - POSTGRES_DB=lindy
     - POSTGRES_PASSWORD=mysecretpassword
   volumes:
     - ../data/storage:/var/lib/postgresql/data
   ports:
     - 5432

  web:
    build:
      context: ..
      dockerfile: deployment/nginx/Dockerfile.dev
    image: todorus/lindy-admin:nginx-dev
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app:app
