version: '3.1'
services:

  app:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/lindy-admin:develop
    environment:
      HOST_NAME: admin.dev
      WEBHOOK_HOST_NAME: example.com
      SECRET_KEY_BASE: 32fbc25fb6cf0b875046c4342fd340b85ad5ba7c9ccca1993c3af44d584caf0f3c3f4b57b50ab20b3b8dee1a212bc61ea7e7f7f0dc2d0562bfe37c57fa54286b
      REDIS_URL: "redis://redis:6379"
    ports:
      - 3000
      - 80
      - 443
    volumes:
      - ../rails-app:/rails-app
    depends_on:
      - storage
      - redis
    links:
      - storage
      - redis
    stdin_open: true
    tty: true
    command: /bin/bash

  worker:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/lindy-admin:develop
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - 3000
      - 80
      - 443
    volumes:
      - ../rails-app:/rails-app
    depends_on:
      - storage
      - redis
    links:
      - storage
      - redis
    command: bundle exec sidekiq

  storage:
    image: postgres:9.6.3
    environment:
       POSTGRES_USER: lindy
       POSTGRES_DB: lindy
       POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432

  redis:
    image: redis
    volumes:
      - ../data/redis:/data
    ports:
      - 6379

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../data/ssl_certs:/var/lib/https-portal
    depends_on:
      - wordpress
      - app
    links:
      - wordpress
      - app
    restart: always
    environment:
      DOMAINS: 'lindy.dev -> http://wordpress:80, admin.dev -> http://app:3000'
      STAGE: local
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
