version: '3.1'
services:

  app:
    image: todorus/lindy-admin:develop
    environment:
      HOST_NAME: TODO
      SECRET_KEY_BASE: TODO
      MOLLIE_API_KEY: TODO
    ports:
      - 3000
      - 80
      - 443
    deploy:
      restart_policy:
        condition: any
        window: 5s
    depends_on:
      - storage
    links:
      - storage:storage
    command: bash -c "rake db:migrate; rails s"

  storage:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: lindy
      POSTGRES_DB: lindy
      POSTGRES_PASSWORD: mysecretpassword
    deploy:
      restart_policy:
        condition: any
        window: 5s
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432

  worker:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/lindy-admin:develop
    environment:
      REDIS_URL: "redis://redis:6379"
      MJ_APIKEY_PUBLIC: TODO
      MJ_APIKEY_PRIVATE: TODO
    ports:
      - 3000
      - 80
      - 443
    volumes:
      - ../rails-app:/rails-app
    depends_on:
      - storage
      - redis
    links:
      - storage
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis
    volumes:
      - ../data/redis:/data
    ports:
      - 6379

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    links:
      - app
    deploy:
      restart_policy:
        condition: any
        window: 5s
    environment:
      DOMAINS: 'lindy.todorus.com -> http://app:3000'
      STAGE: production
