version: '3.1'
services:

  app:
    image: todorus/lindy-admin:develop
    environment:
      HOST_NAME: lindy.todorus.com
      WEBHOOK_HOST_NAME: lindy.todorus.com
      SECRET_KEY_BASE: 32fbc25fb6cf0b875046c4342fd340b85ad5ba7c9ccca1993c3af44d584caf0f3c3f4b57b50ab20b3b8dee1a212bc61ea7e7f7f0dc2d0562bfe37c57fa54286b
      REDIS_URL: "redis://redis:6379"
    ports:
      - 3000
      - 80
      - 443
    restart: unless-stopped
    depends_on:
      - storage
      - redis
    links:
      - storage
      - redis
    entrypoint: ["/rails-app/docker-entrypoint.sh"]
    command: bash -c "rake db:migrate; rails s"


  storage:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: lindy
      POSTGRES_DB: lindy
      POSTGRES_PASSWORD: mysecretpassword
    restart: unless-stopped
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432

  worker:
    image: todorus/lindy-admin:develop
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - 3000
      - 80
      - 443
    restart: unless-stopped
    depends_on:
      - storage
      - redis
    links:
      - storage
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis
    volumes:
      - ../data/redis:/data
    ports:
      - 6379
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../data/ssl_certs:/var/lib/https-portal
    depends_on:
      - app
    links:
      - app
    restart: unless-stopped
    environment:
      DOMAINS: 'lindy.todorus.com -> http://app:3000'
      STAGE: staging
