version: '2'
services:

  app:
    image: todorus/lindy-admin:develop
    ports:
      - 3000
    depends_on:
      - storage
    links:
      - storage:storage
    command: bash -c "rake db:migrate; rails s"

  storage:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=lindy
      - POSTGRES_DB=lindy
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432

  web:
    image: todorus/lindy-admin:nginx-dev
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app:app
