version: '3.1'
services:

  test:
    build:
      context: ..
      dockerfile: deployment/test/Dockerfile
    image: todorus/lindy-admin:test
    environment:
      HOST_NAME: admin.test
      WEBHOOK_HOST_NAME: example.com
      SECRET_KEY_BASE: 32fbc25fb6cf0b875046c4342fd340b85ad5ba7c9ccca1993c3af44d584caf0f3c3f4b57b50ab20b3b8dee1a212bc61ea7e7f7f0dc2d0562bfe37c57fa54286b
      REDIS_URL: "redis://redis:6379"
    ports:
      - 3000
      - 80
      - 443
    volumes:
      - ../rails-app:/rails-app
    depends_on:
      - storage
    links:
      - storage
    stdin_open: true
    tty: true
    command: /bin/bash

  storage:
    image: postgres:9.6.3
    environment:
       POSTGRES_USER: lindy
       POSTGRES_DB: lindy
       POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432

  # worker:
  #   image: todorus/lindy-admin:develop
  #   environment:
  #     REDIS_URL: "redis://redis:6379"
  #   ports:
  #     - 3000
  #     - 80
  #     - 443
  #   restart: unless-stopped
  #   depends_on:
  #     - storage
  #     - redis
  #   links:
  #     - storage
  #     - redis
  #   command: bundle exec sidekiq

  redis:
    image: redis
    volumes:
      - ../data/redis:/data
    ports:
      - 6379
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    ports:
     - '80:80'
     - '443:443'
    volumes:
     - ../data/ssl_certs:/var/lib/https-portal
    depends_on:
     - test
    links:
     - test
    restart: always
    environment:
     DOMAINS: 'lindy.admin.test -> http://test:3000'
     STAGE: local
     # STAGE: 'production'
     # FORCE_RENEW: 'true'
